import React from 'react';
import { Shipment } from '../types';
import { Logo } from './Logo';
import { Truck, MapPin, Package, Calendar } from 'lucide-react';

interface Props {
  shipment: Shipment;
}

export const PrintableShipment: React.FC<Props> = ({ shipment }) => {
  return (
    <div id="printable-area" className="bg-white text-slate-900 p-12 max-w-[297mm] mx-auto min-h-[210mm] text-sm font-sans shadow-lg print:shadow-none print:w-full">
      
      {/* Header */}
      <div className="border-b-4 border-[#003d5b] pb-6 mb-8 flex justify-between items-start">
        <div>
          <Logo className="h-12 w-auto text-[#003d5b] mb-2" variant="full" />
          <p className="text-slate-500 font-bold text-lg">Shipping Manifest</p>
        </div>
        <div className="text-right">
          <div className="bg-slate-100 px-4 py-2 rounded-lg inline-block print:border print:border-slate-300">
            <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-widest">Tracking Number</span>
            <span className="font-mono text-lg font-bold">{shipment.trackingNumber || 'PENDING'}</span>
          </div>
        </div>
      </div>

      {/* Manifest Grid */}
      <div className="grid grid-cols-4 gap-8 mb-12">
        <div className="space-y-4">
          <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] flex items-center gap-2">
            <MapPin className="w-3 h-3" /> Origin Port
          </h4>
          <p className="font-bold text-base">{shipment.origin || 'N/A'}</p>
        </div>
        <div className="space-y-4">
          <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] flex items-center gap-2">
            <MapPin className="w-3 h-3" /> Destination
          </h4>
          <p className="font-bold text-base">{shipment.destination || 'N/A'}</p>
        </div>
        <div className="space-y-4">
          <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] flex items-center gap-2">
            <Truck className="w-3 h-3" /> Logistics Provider
          </h4>
          <p className="font-bold text-base">{shipment.carrier || 'N/A'}</p>
          <p className="text-xs text-slate-500 uppercase font-bold">{shipment.method} Freight</p>
        </div>
        <div className="space-y-4">
          <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] flex items-center gap-2">
            <Calendar className="w-3 h-3" /> Scheduled ETA
          </h4>
          <p className="font-bold text-base">{shipment.eta || 'TBD'}</p>
        </div>
      </div>

      {/* Inventory Table */}
      <div className="mb-12">
        <h4 className="text-[10px] font-black text-slate-400 uppercase tracking-[0.2em] mb-4">Cargo Details</h4>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-50 border-y border-slate-200">
              <th className="p-4 text-[10px] font-bold uppercase text-slate-500 tracking-wider">Lot / Container ID</th>
              <th className="p-4 text-[10px] font-bold uppercase text-slate-500 tracking-wider">Type</th>
              <th className="p-4 text-[10px] font-bold uppercase text-slate-500 tracking-wider">Quantity</th>
              <th className="p-4 text-[10px] font-bold uppercase text-slate-500 tracking-wider text-right">Status</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-slate-100">
              <td className="p-4 font-mono font-bold">{shipment.trackingNumber || 'UNASSIGNED'}</td>
              <td className="p-4 uppercase text-xs font-bold text-slate-600">{shipment.method}</td>
              <td className="p-4">Bulk Cargo (Verified)</td>
              <td className="p-4 text-right">
                <span className="px-2 py-1 bg-sky-50 text-sky-700 rounded-md text-[10px] font-black uppercase border border-sky-100">
                  {shipment.status}
                </span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* Footer / Signature Area */}
      <div className="mt-auto pt-12 flex justify-between items-end">
        <div className="text-[10px] text-slate-400 space-y-1">
          <p>Generated by Usuppli Global Logistics System</p>
          <p>Institutional Compliance Verified: ISO 28000</p>
          <p>Date Generated: {new Date().toLocaleString()}</p>
        </div>
        <div className="w-64">
          <div className="border-b-2 border-slate-900 mb-2"></div>
          <p className="text-[10px] font-black text-slate-400 uppercase text-center tracking-[0.2em]">Authorized Signature</p>
        </div>
      </div>

    </div>
  );
};
